Feature/HM-9-[Admin]-Create admin microservice
rosteslav/HomesBE pull request #16
Opened 2023-11-16 09:51 UTC by petarbelchev

The Admin microservice has been created. It has two endpoints for now:
1. GET /Admins/brokers - Returns all users that have the Broker role;
2. POST /Admins/properties - Admins can attach .csv file with properties in format "Type;NumberOfRooms;District;Space;Floor;TotalFloorsInBuilding;SellerId;BrokerId(can be missing)" per row and per property.

On the Properties microservice, an "AddMultiple" endpoint has been created, which expects and inserts the properties passed from the Admins microservice.

2023-11-17 10:08 UTC, rosteslav requested changes

2023-11-17 10:08 UTC, rosteslav commented on src/Properties/Properties.Application/Features/Properties/Commands/AddMultipleProperties/AddMultiplePropertiesCommandHandler.cs
> +        private readonly ILogger<AddMultiplePropertiesCommandHandler> _logger = logger;
Not used

2023-11-17 10:08 UTC, rosteslav commented on src/Properties/Properties.Application/Features/Properties/Commands/AddMultipleProperties/AddMultiplePropertiesCommandHandler.cs
> +            return new Response { Status = "Success", Message = $"{result} properties have been successfully added" };
Don't make a response here

2023-11-17 10:08 UTC, rosteslav commented on src/Properties/Properties.Application/Features/Properties/Commands/AddMultipleProperties/AddMultiplePropertiesCommand.cs
> +    public class AddMultiplePropertiesCommand : IRequest<Response>
Don't return response here

2023-11-17 10:08 UTC, rosteslav commented on src/Properties/Properties.Api/Controllers/PropertiesController.cs
> +            return Ok(await _mediator.Send(command));
Should bahave like add single, return nocontent

2023-11-17 10:08 UTC, rosteslav commented on src/Properties/Properties.Application/Models/Response.cs
> +    public class Response
Not needed

2023-11-17 10:08 UTC, rosteslav commented on src/Properties/Properties.Application/Features/Properties/Commands/AddMultipleProperties/AddMultiplePropertiesCommandHandler.cs
> +            int result = await _propertiesRepository.AddMultiple(properties);
No return here - AddMultiple should be void (Task)

2023-11-17 10:08 UTC, rosteslav commented on src/Properties/Properties.Infrasructure/Repositories/PropertiesRepository.cs
> +            return result;
Behave like Add single

2023-11-17 10:08 UTC, rosteslav commented on src/Properties/Properties.Infrasructure/Repositories/PropertiesRepository.cs
> +                result = await _context.SaveChangesAsync();
no result -> if something's wrong -> exception

2023-11-17 10:08 UTC, rosteslav commented on src/Properties/Properties.Infrasructure/Repositories/PropertiesRepository.cs
> +            int result = 0;
Not needed

2023-11-17 10:08 UTC, rosteslav commented on src/Properties/Properties.Application/Contracts/IPropertiesRepository.cs
> +        Task<int> AddMultiple(IEnumerable<Property> properties);
Taks, like Add

2023-11-17 10:08 UTC, rosteslav commented on src/Admins/Admins.Api/Controllers/AdminsController.cs
> +        private readonly ILogger<AdminsController> _logger = logger;
log on every endpoing hit, like on other controllers

2023-11-17 10:08 UTC, rosteslav commented on src/Properties/Properties.Api/Controllers/PropertiesController.cs
> +        {
Log that the endpoint is hit

2023-11-17 10:08 UTC, rosteslav commented on src/Admins/Admins.Api/Controllers/AdminsController.cs
> +            return Ok(response);
Return NoContent, if error -> throw

2023-11-17 10:08 UTC, rosteslav commented on src/Admins/Admins.Api/Program.cs
> +services.AddIdentity<IdentityUser, IdentityRole>(options =>
We don't need this since we are not registering users here

2023-11-17 10:08 UTC, rosteslav commented on src/Admins/Admins.Api/Program.cs
> +    .AddEntityFrameworkStores<AdminsDbContext>()
We are not doing any of that here, we work with tokens only

2023-11-17 10:08 UTC, rosteslav commented on src/Admins/Admins.Api/Properties/launchSettings.json
> +        "PropertiesMicroserviceHost": "http://localhost:5220",
We write directly to the DB

2023-11-17 10:08 UTC, rosteslav commented on src/Admins/Admins.Api/Properties/launchSettings.json
> +        "PropertiesMicroserviceHost": "http://localhost:5220",
Not needed

2023-11-17 10:08 UTC, rosteslav commented on src/Admins/Admins.Application/Contracts/IAdminRepository.cs
> +        Task<IEnumerable<IdentityUser>> GetAllBrokers();
Add AddMultipleProperties as it is admin functionality

2023-11-17 10:08 UTC, rosteslav commented on src/Admins/Admins.Application/Features/Admins/Commands/AddMultipleProperties/AddMultiplePropertiesCommand.cs
> +        public string JWT { get; set; }
Lets not use JWT this way, not needed here

2023-11-17 10:08 UTC, rosteslav commented on src/Admins/Admins.Application/Features/Admins/Commands/AddMultipleProperties/AddMultiplePropertiesCommandHandler.cs
> +        private readonly ILogger<AddMultiplePropertiesCommandHandler> _logger = logger;
Log something

2023-11-17 10:08 UTC, rosteslav commented on src/Admins/Admins.Application/Features/Admins/Commands/AddMultipleProperties/AddMultiplePropertiesCommandHandler.cs
> +        {
Don't send them anywhere, write it to the DB straightaway

2023-11-17 10:08 UTC, rosteslav commented on src/Admins/Admins.Application/Features/Admins/Commands/AddMultipleProperties/AddMultiplePropertiesCommandHandler.cs
> +                    string[] data = line.Split(';', StringSplitOptions.RemoveEmptyEntries);
User comma as a separator, let keep it right, CSV - comma separated values

2023-11-17 10:08 UTC, rosteslav commented on src/Admins/Admins.Application/Features/Admins/Commands/AddMultipleProperties/AddMultiplePropertiesCommandHandler.cs
> +                SellerId = data[6]
BrokerId Also

2023-11-17 10:08 UTC, rosteslav commented on src/Admins/Admins.Application/Features/Admins/Commands/AddMultipleProperties/AddMultiplePropertiesCommandHandler.cs
> +            if (data.Length > 7)
Make constants to make changes easy - Set constants in the beginning of the file:
- public const int TypePosition = 0;
- public const int TotalNumberOfPossition = 7;
this way when we make a change on fiestld just change the consts, not the logic

2023-11-17 10:08 UTC, rosteslav commented on src/Admins/Admins.Application/Features/Admins/Commands/AddMultipleProperties/AddMultiplePropertiesCommandHandler.cs
> +        {
This method sets user id to be aur, and here we don't want that - admin bulk inserts the properties - he is not the seller of them. This is a helper function if we migrate from another site

2023-11-17 10:08 UTC, rosteslav commented on src/Admins/Admins.Api/Controllers/AdminsController.cs
> +                JWT = jwt,
No JWT here

2023-11-17 10:08 UTC, rosteslav commented on src/Admins/Admins.Api/Controllers/AdminsController.cs
> +            Request.Headers.TryGetValue("Authorization", out StringValues jwt);
Remove this since JWT will not be used in this way

2023-11-17 10:08 UTC, rosteslav commented on src/Admins/Admins.Application/Models/Response.cs
> +    public class Response
Remove this all together

2023-11-17 10:08 UTC, rosteslav commented on src/Admins/Admins.Infrastructure/Persistence/Configuration/ConnectionsConfig.cs
> +    public class ConnectionsConfig
Move this to common and use it on all the other places as it's the same for every project

2023-11-17 10:08 UTC, rosteslav commented on src/Admins/Admins.Infrastructure/Persistence/AdminsDbContext.cs
> +            modelBuilder.Entity<IdentityRole>().ToTable("Roles", "security");
Don't need all of those.. only the user to read from. Maybe Roles and UserRoles as well, if  _userManager.GetUsersInRoleAsync(UserRoles.Broker) needs it. research what is needed

2023-11-17 10:08 UTC, rosteslav commented on src/Admins/Admins.Infrastructure/Persistence/AdminsDbContext.cs
> +            base.OnModelCreating(modelBuilder);
You will need properties as well in order to write to

2023-11-17 10:08 UTC, rosteslav commented on src/Admins/Admins.Infrastructure/Repositories/AdminRepository.cs
> +        private readonly UserManager<IdentityUser> _userManager = userManager;
Have Write to Properties as well, we'll do it here

2023-11-17 15:55 UTC, petarbelchev commented on src/Admins/Admins.Api/Controllers/AdminsController.cs
> +        private readonly ILogger<AdminsController> _logger = logger;
Done!

2023-11-17 15:56 UTC, petarbelchev commented on src/Admins/Admins.Api/Controllers/AdminsController.cs
> +            Request.Headers.TryGetValue("Authorization", out StringValues jwt);
Done!

2023-11-17 15:56 UTC, petarbelchev commented on src/Admins/Admins.Api/Controllers/AdminsController.cs
> +                JWT = jwt,
Done!

2023-11-17 15:56 UTC, petarbelchev commented on src/Admins/Admins.Api/Controllers/AdminsController.cs
> +            return Ok(response);
Done!

2023-11-17 15:57 UTC, petarbelchev commented on src/Admins/Admins.Api/Program.cs
> +services.AddIdentity<IdentityUser, IdentityRole>(options =>
Done!

2023-11-17 15:57 UTC, petarbelchev commented on src/Admins/Admins.Api/Program.cs
> +    .AddEntityFrameworkStores<AdminsDbContext>()
Done!

2023-11-17 15:57 UTC, petarbelchev commented on src/Admins/Admins.Api/Properties/launchSettings.json
> +        "PropertiesMicroserviceHost": "http://localhost:5220",
Done!

2023-11-17 15:58 UTC, petarbelchev commented on src/Admins/Admins.Application/Contracts/IAdminRepository.cs
> +        Task<IEnumerable<IdentityUser>> GetAllBrokers();
Done!

2023-11-17 15:58 UTC, petarbelchev commented on src/Admins/Admins.Application/Features/Admins/Commands/AddMultipleProperties/AddMultiplePropertiesCommand.cs
> +        public string JWT { get; set; }
Done!

2023-11-17 16:01 UTC, petarbelchev commented on src/Admins/Admins.Application/Features/Admins/Commands/AddMultipleProperties/AddMultiplePropertiesCommandHandler.cs
> +        private readonly ILogger<AddMultiplePropertiesCommandHandler> _logger = logger;
Done!

2023-11-17 16:01 UTC, petarbelchev commented on src/Admins/Admins.Application/Features/Admins/Commands/AddMultipleProperties/AddMultiplePropertiesCommandHandler.cs
> +                    string[] data = line.Split(';', StringSplitOptions.RemoveEmptyEntries);
Done!

2023-11-17 16:02 UTC, petarbelchev commented on src/Admins/Admins.Application/Features/Admins/Commands/AddMultipleProperties/AddMultiplePropertiesCommandHandler.cs
> +                SellerId = data[6]
Done!

2023-11-17 16:02 UTC, petarbelchev commented on src/Admins/Admins.Application/Features/Admins/Commands/AddMultipleProperties/AddMultiplePropertiesCommandHandler.cs
> +            if (data.Length > 7)
Done!

2023-11-17 16:02 UTC, petarbelchev commented on src/Admins/Admins.Application/Features/Admins/Commands/AddMultipleProperties/AddMultiplePropertiesCommandHandler.cs
> +        {
Done!

2023-11-17 16:02 UTC, petarbelchev commented on src/Admins/Admins.Application/Models/Response.cs
> +    public class Response
Done!

2023-11-17 16:03 UTC, petarbelchev commented on src/Admins/Admins.Infrastructure/Persistence/AdminsDbContext.cs
> +            base.OnModelCreating(modelBuilder);
Done!

2023-11-17 16:23 UTC, petarbelchev commented on src/Admins/Admins.Infrastructure/Persistence/AdminsDbContext.cs
> +            modelBuilder.Entity<IdentityRole>().ToTable("Roles", "security");
Done!

2023-11-17 16:26 UTC, petarbelchev commented on src/Admins/Admins.Infrastructure/Persistence/Configuration/ConnectionsConfig.cs
> +    public class ConnectionsConfig
Done!

2023-11-17 16:27 UTC, petarbelchev commented on src/Admins/Admins.Infrastructure/Repositories/AdminRepository.cs
> +        private readonly UserManager<IdentityUser> _userManager = userManager;
Done!

2023-11-17 16:28 UTC, petarbelchev commented on src/Properties/Properties.Api/Controllers/PropertiesController.cs
> +        {
Done!

2023-11-17 16:29 UTC, petarbelchev commented on src/Properties/Properties.Api/Controllers/PropertiesController.cs
> +            return Ok(await _mediator.Send(command));
Done!

2023-11-17 16:29 UTC, petarbelchev commented on src/Properties/Properties.Application/Contracts/IPropertiesRepository.cs
> +        Task<int> AddMultiple(IEnumerable<Property> properties);
Done!

2023-11-17 16:30 UTC, petarbelchev commented on src/Properties/Properties.Application/Features/Properties/Commands/AddMultipleProperties/AddMultiplePropertiesCommand.cs
> +    public class AddMultiplePropertiesCommand : IRequest<Response>
Done!

2023-11-17 16:30 UTC, petarbelchev commented on src/Properties/Properties.Application/Features/Properties/Commands/AddMultipleProperties/AddMultiplePropertiesCommandHandler.cs
> +        private readonly ILogger<AddMultiplePropertiesCommandHandler> _logger = logger;
Done!

2023-11-17 16:30 UTC, petarbelchev commented on src/Properties/Properties.Application/Features/Properties/Commands/AddMultipleProperties/AddMultiplePropertiesCommandHandler.cs
> +            int result = await _propertiesRepository.AddMultiple(properties);
Done!

2023-11-17 16:30 UTC, petarbelchev commented on src/Properties/Properties.Application/Features/Properties/Commands/AddMultipleProperties/AddMultiplePropertiesCommandHandler.cs
> +            return new Response { Status = "Success", Message = $"{result} properties have been successfully added" };
Done!

2023-11-17 16:31 UTC, petarbelchev commented on src/Properties/Properties.Application/Models/Response.cs
> +    public class Response
Done!

2023-11-17 16:31 UTC, petarbelchev commented on src/Properties/Properties.Infrasructure/Repositories/PropertiesRepository.cs
> +            int result = 0;
Done!

2023-11-17 16:32 UTC, petarbelchev commented on src/Properties/Properties.Infrasructure/Repositories/PropertiesRepository.cs
> +                result = await _context.SaveChangesAsync();
Done!

2023-11-17 16:32 UTC, petarbelchev commented on src/Properties/Properties.Infrasructure/Repositories/PropertiesRepository.cs
> +            return result;
Done!

2023-11-18 10:39 UTC, rosteslav requested changes

2023-11-18 10:39 UTC, rosteslav commented on src/Admins/Admins.Infrastructure/Persistence/AdminsDbContext.cs
> +    public class AdminsDbContext(DbContextOptions<AdminsDbContext> options) : IdentityDbContext<IdentityUser>(options)
Try If it works without being IdentityDbContext<IdentityUser>(options), just a DbContext. We are not registering users here after all, nor logging them

2023-11-18 10:39 UTC, rosteslav commented on src/Admins/Admins.Application/Features/Admins/Commands/AddMultipleProperties/AddMultiplePropertiesCommandHandler.cs
> +        private async Task<IEnumerable<Property>> MapPropertiesFromFile(IFormFile file)
This logic should not be here - logic in infrastructure

2023-11-18 10:39 UTC, rosteslav commented on src/Admins/Admins.Application/Features/Admins/Commands/AddMultipleProperties/AddMultiplePropertiesCommandHandler.cs
> +        private static Property MapPropertyModel(string[] data)
This is also login for infrastructure

2023-11-18 11:43 UTC, petarbelchev commented on src/Admins/Admins.Infrastructure/Persistence/AdminsDbContext.cs
> +    public class AdminsDbContext(DbContextOptions<AdminsDbContext> options) : IdentityDbContext<IdentityUser>(options)
I tried this, but it doesn't work like that.

2023-11-18 12:19 UTC, petarbelchev commented on src/Admins/Admins.Application/Features/Admins/Commands/AddMultipleProperties/AddMultiplePropertiesCommandHandler.cs
> +        private async Task<IEnumerable<Property>> MapPropertiesFromFile(IFormFile file)
Done!

2023-11-18 12:19 UTC, petarbelchev commented on src/Admins/Admins.Application/Features/Admins/Commands/AddMultipleProperties/AddMultiplePropertiesCommandHandler.cs
> +        private static Property MapPropertyModel(string[] data)
Done!

2023-11-18 13:06 UTC, rosteslav approved these changes

2023-11-18 13:06 UTC, merged