Feature/HM-30-[Properties]-Add timestamp to properties
rosteslav/HomesBE pull request #30
Opened 2023-11-21 15:03 UTC by petarbelchev

A timestamp has been added to the Property entity.

2023-11-21 17:03 UTC, rosteslav requested changes

2023-11-21 17:03 UTC, rosteslav commented on src/Properties/Properties.Application/Mapper/PropertyProfile.cs
> +                .ForMember(x => x.CreatedOnLocalTime, opt => opt.MapFrom(src => src.CreatedOnUtcTime.ToLocalTime()));
don't kill ReverseMap, instead add this:
.ReverseMap()
.ForPath(src => src.CreatedOnUtcTime, opt => opt.MapFrom(x => x.CreatedOnLocalTime.ToUniversalTime()));
which does it the other way around

2023-11-21 20:27 UTC, petarbelchev commented on src/Properties/Properties.Application/Mapper/PropertyProfile.cs
> +                .ForMember(x => x.CreatedOnLocalTime, opt => opt.MapFrom(src => src.CreatedOnUtcTime.ToLocalTime()));
I removed the ReverseMap because we currently don't use it, but you are right we might use it in the future?

2023-11-21 22:12 UTC, rosteslav requested changes

2023-11-21 22:12 UTC, rosteslav commented on src/Properties/Properties.Application/Mapper/PropertyProfile.cs
> -                .ForMember(x => x.CreatedOnLocalTime, opt => opt.MapFrom(src => src.CreatedOnUtcTime.ToLocalTime()));
Don't remove for member, just add this 🤣

2023-11-21 22:14 UTC, rosteslav commented on src/Properties/Properties.Application/Mapper/PropertyProfile.cs
> -                .ForMember(x => x.CreatedOnLocalTime, opt => opt.MapFrom(src => src.CreatedOnUtcTime.ToLocalTime()));
It will not work without tolocaltime, this addition is just in order to work the other way around as well

2023-11-22 06:08 UTC, petarbelchev commented on src/Properties/Properties.Application/Mapper/PropertyProfile.cs
> -                .ForMember(x => x.CreatedOnLocalTime, opt => opt.MapFrom(src => src.CreatedOnUtcTime.ToLocalTime()));
Right! :D I usually use ForMember again after ReverseMap... now I will know the right way! :)

2023-11-22 08:58 UTC, rosteslav approved these changes

2023-11-22 08:58 UTC, merged