HM-42 (Add ImageURL to AdditionalUserData) and HM-60 (small bugfix)
rosteslav/HomesBE pull request #46
Opened 2023-11-29 14:25 UTC by viktorgkw

2023-11-29 18:41 UTC, rosteslav requested changes

2023-11-29 18:41 UTC, rosteslav commented on src/Images/Images.Api/Controllers/UserImagesController.cs
> +        [ProducesResponseType(StatusCodes.Status200OK)]
Type!

2023-11-29 18:41 UTC, rosteslav commented on src/Images/Images.Api/Controllers/UserImagesController.cs
> +        [ProducesResponseType(StatusCodes.Status200OK)]
200 of a what?

2023-11-29 18:41 UTC, rosteslav commented on src/Images/Images.Api/Controllers/UserImagesController.cs
> +            return Ok();
NoContent()

2023-11-29 18:41 UTC, rosteslav commented on src/Images/Images.Application/Contracts/IImagesRepository.cs
> +        Task AddUserImage(string imageUrl, string userId);
What's the difference, why AddPropertyImage is based on Image and AddUserImage is based on string?

2023-11-29 18:41 UTC, rosteslav commented on src/Images/Images.Domain/Entities/AdditionalUserData.cs
> +        [Key]
POCO Object - no logic here!

2023-11-29 18:41 UTC, rosteslav commented on src/Images/Images.Domain/Entities/AdditionalUserData.cs
> +﻿using System.ComponentModel.DataAnnotations;
no usings here - clean

2023-11-29 18:41 UTC, rosteslav commented on src/Images/Images.Infrastructure/Migrations/20231125173857_InitialCreate.cs
Don't modify auto-generated file

2023-11-29 18:41 UTC, rosteslav commented on src/Images/Images.Infrastructure/Persistence/ImagesDbContext.cs
> +            modelBuilder.Entity<AdditionalUserData>(entity =>
This is not owned here -> no migrations here
This is owned in Auth microservice

2023-11-29 19:15 UTC, viktorgkw commented on src/Images/Images.Application/Contracts/IImagesRepository.cs
> +        Task AddUserImage(string imageUrl, string userId);
AddPropertyImage accepts Image that has PropertyId and ImageURL which then adds a new record in the Images table. On the other side AddUserImage updates the ImageURL in the user's additionaluserdata data.

```
await _context.AdditionalUserData
        .Where(addData => addData.UserId == userId)
        .ExecuteUpdateAsync(p => p
            .SetProperty(data => data.ImageURL, data => imageUrl));
```

So it doesn't add a record in the Image table.

2023-11-29 20:58 UTC, rosteslav requested changes

2023-11-29 20:58 UTC, rosteslav commented on src/Images/Images.Infrastructure/Migrations/20231125173857_InitialCreate.cs
Don't touch auto generated files :) Sory if I got confused

2023-11-29 20:58 UTC, rosteslav commented on src/Images/Images.Infrastructure/Persistence/ImagesDbContext.cs
> +                entity.ToTable("AdditionalData", "security");
This is not handled here! add like here:
entity.ToTable("Images", "properties", i => i.ExcludeFromMigrations());

2023-11-29 20:58 UTC, rosteslav commented on src/Auth/Auth.Domain/Entities/AdditionalUserData.cs
No         [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
- keep it pure

2023-11-29 20:58 UTC, rosteslav commented on src/Images/Images.Application/Contracts/IImagesRepository.cs
> +        Task AddUserImage(string imageUrl, string userId);
I see now. Ok, separate this repository to two - one for the profile images and one for the property images. There you should keep names as Add, Delete, etc. ImgbbService stays one, for sure

2023-11-30 19:28 UTC, rosteslav approved these changes

2023-11-30 19:28 UTC, merged