Feature/HM-46-Properties-Make-a-filter-in-all-properties
rosteslav/HomesBE pull request #47
Opened 2023-11-29 15:24 UTC by petarbelchev

Filter in all properties endpoint has been implemented.

2023-11-29 20:35 UTC, rosteslav requested changes

2023-11-29 20:35 UTC, rosteslav commented on src/Properties/Properties.Infrastructure/Repositories/PropertiesRepository.cs
> +                                (query.Neighbourhood == null || query.Neighbourhood.Contains(property.Neighbourhood)) &&
What if the query is null? User "?." operator

2023-11-30 06:41 UTC, petarbelchev commented on src/Properties/Properties.Infrastructure/Repositories/PropertiesRepository.cs
> +                                (query.Neighbourhood == null || query.Neighbourhood.Contains(property.Neighbourhood)) &&
There is no such option. Even if we send an "empty" request to GET /Properties/all, the Model Binder initializes the GetAllPropertiesQuery model with all properties set to default values.

However, if I need to check for null the "query" I need to use the "==" operator because the compiler doesn't let me use the '?.' null propagating operator inside an expression tree lambda.

2023-11-30 19:45 UTC, rosteslav commented on src/Properties/Properties.Infrastructure/Repositories/PropertiesRepository.cs
> +                                (query.Neighbourhood == null || query.Neighbourhood.Contains(property.Neighbourhood)) &&
I see.
However it is a responsibility of every method to check the input.
Null can be passed anyways.
Just put this in the beginning of the method
`if (query == null)`
    `    query = new();`

2023-12-01 09:02 UTC, rosteslav approved these changes

2023-12-01 09:02 UTC, merged