HM-52 [Auth] Make Preferences Entity
rosteslav/HomesBE pull request #50
Opened 2023-11-30 14:20 UTC by ChrisIvanov

2023-11-30 19:55 UTC, rosteslav requested changes

2023-11-30 19:55 UTC, rosteslav commented on src/Auth/Auth.Infrastucture/Persistence/ApplicationDbContext.cs
> +
describe id as well
`entity.Property(e => e.Id)`
`    .HasColumnName("id");`

2023-11-30 19:55 UTC, rosteslav commented on src/Auth/Auth.Domain/Entities/Preferences.cs
> +        public string PriceHigherEnd { get; set; }
decimal

2023-11-30 19:55 UTC, rosteslav commented on src/Auth/Auth.Infrastucture/Persistence/ApplicationDbContext.cs
> +                .HasColumnType("character varying")
real .. I think

2023-11-30 19:55 UTC, rosteslav commented on src/Auth/Auth.Domain/Entities/Preferences.cs
> +        public string UserId { get; set; }
required, the C# keyword

2023-11-30 19:55 UTC, rosteslav commented on src/Auth/Auth.Domain/Entities/Preferences.cs
> +        public int Id { get; set; }
reuquired

2023-12-01 11:55 UTC, ChrisIvanov commented on src/Auth/Auth.Infrastucture/Persistence/ApplicationDbContext.cs
> +
Should I state a type for the Id column?

2023-12-01 14:54 UTC, rosteslav approved these changes

2023-12-01 14:58 UTC, merged