Feature/HM-61-Properties-New endpoint GET /PropertyOptions/filter
rosteslav/HomesBE pull request #56
Opened 2023-12-02 09:19 UTC by petarbelchev

A new GET /PropertyOptions/filter endpoint has been created.

2023-12-02 14:26 UTC, rosteslav requested changes

2023-12-02 14:26 UTC, rosteslav commented on src/Properties/Properties.Infrastructure/Repositories/PropertyOptionsRepository.cs
> +            model.BuildingType = await _context.BuildingTypes.Select(bt => bt.Description).ToListAsync();
Done this way, this is a sync code, you assign one thing after the other, every row await for the completion of the one before, so it writes 'async' but, in fact isn't. Better init this `var optionsWithFilterModel = new PropertyOptionsWithFilterModel();` in this method as well in order to get all the components in async way. and then return the object, not just enrich it like you are doing currently

2023-12-02 14:26 UTC, rosteslav commented on src/Properties/Properties.Infrastructure/Repositories/PropertyOptionsRepository.cs
> +            model.PublishedOn = await _context.PublishedOn
try to do this in async way as well, just ensure everything is finished with `Task.WaitAll()` or something

2023-12-02 17:39 UTC, petarbelchev commented on src/Properties/Properties.Infrastructure/Repositories/PropertyOptionsRepository.cs
> +            model.PublishedOn = await _context.PublishedOn
With the limitations of our database, it's going to be fun to send multiple queries to it at the same time.

2023-12-03 17:29 UTC, rosteslav approved these changes

2023-12-03 17:29 UTC, merged