Feature/HM-65-[Properties]-GET /Properties now also returns the property ID.
rosteslav/HomesBE pull request #58
Opened 2023-12-02 14:30 UTC by petarbelchev

The GET /Properties now also returns the property ID.
The Select expression in the Properties repository has been replaced with an AutoMapper configuration.

2023-12-02 16:44 UTC, rosteslav requested changes

2023-12-02 16:44 UTC, rosteslav commented on src/Properties/Properties.Api/Controllers/PropertiesController.cs
>          public async Task<IActionResult> Get()
line 52 have that too

2023-12-02 16:44 UTC, rosteslav commented on src/Properties/Properties.Application/Mapper/PropertyProfile.cs
> +                .ForMember(x => x.CreatedOnLocalTime, opt => opt.MapFrom(src => src.Property.CreatedOnUtcTime.ToLocalTime()))
this is not right. If you see repetition Exposure-Exposure; Furnishment-Furnishment - this is not right, it should be automatic.
just at .`ForMember(x => x, opt => opt.MapFrom(src => src.Property))`
and add map for that too, if not present. This is done elsewhere in the code

2023-12-02 16:44 UTC, rosteslav commented on src/Properties/Properties.Infrastructure/Repositories/PropertiesRepository.cs
> +                    (pua, image) => new PropertyProjectToModel
This worked before, why you need to do it so hard, just in order to all an ID. I see this as a three file change task

2023-12-03 07:41 UTC, petarbelchev commented on src/Properties/Properties.Infrastructure/Repositories/PropertiesRepository.cs
> +                    (pua, image) => new PropertyProjectToModel
The changes were numerous because the task was to add a response ID to the GET /Properties endpoint, but not to the GET /Properties/{id}. Because of that, I needed to separate the common logic they both use.

I moved the logic from here to the mapper profile to avoid repeating the same Select logic.

2023-12-03 08:18 UTC, petarbelchev commented on src/Properties/Properties.Application/Mapper/PropertyProfile.cs
> +                .ForMember(x => x.CreatedOnLocalTime, opt => opt.MapFrom(src => src.Property.CreatedOnUtcTime.ToLocalTime()))
I already tried this, but encountered the following error:
`System.ArgumentException: Expression 'x => x' must resolve to a top-level member and not any child object's properties`.

However, I found a way to avoid repeating the properties using `.IncludeMembers()`.

2023-12-03 17:27 UTC, rosteslav approved these changes

2023-12-03 17:27 UTC, merged