Recommended properties (top 6) endpoint.
rosteslav/HomesBE pull request #83
Opened 2023-12-18 17:42 UTC by viktorgkw

2023-12-20 09:21 UTC, rosteslav requested changes

2023-12-20 09:21 UTC, rosteslav commented on src/Properties/Properties.Api/Controllers/PropertiesController.cs
> +        [ProducesResponseType(
one row

2023-12-20 09:21 UTC, rosteslav commented on src/Properties/Properties.Api/Controllers/PropertiesController.cs
> +        public async Task<IActionResult> Recommended()
it can be also 401 Unauthorized (not logged), 403 Forbidden(not a right role)

2023-12-20 09:21 UTC, rosteslav commented on src/Properties/Properties.Application/Features/Properties/Queries/GetRecommended/GetRecommendedQuery.cs
> +        IRequest<IEnumerable<GetAllPropertiesOutputModel>> { }
one row, { } on the next

2023-12-20 09:21 UTC, rosteslav commented on src/Properties/Properties.Infrastructure/Repositories/PropertiesRepository.cs
> +                .Take(6)
this is last, right before ToListAsync

2023-12-20 09:21 UTC, rosteslav commented on src/Properties/Properties.Infrastructure/Repositories/PropertiesRepository.cs
> +                    Id = pi.Property.Id,
mapper?

2023-12-20 09:21 UTC, rosteslav commented on src/Properties/Properties.Infrastructure/Repositories/PropertiesRepository.cs
> +                .ToListAsync();
give ToListAsync a token, always mind cancellation token, when a executing a long-lasting operation!

2023-12-20 20:36 UTC, rosteslav requested changes

2023-12-20 20:36 UTC, rosteslav commented on src/Properties/Properties.Application/Features/Properties/Queries/GetRecommended/GetRecommendedQueryHandler.cs
> +        {
Use => syntax, skipping `return`

2023-12-20 20:36 UTC, rosteslav commented on src/Properties/Properties.Infrastructure/Repositories/PropertiesRepository.cs
> +                .Take(6)
This should be a config. Even if not - if should be a const, only 0, 1 and -1 are allowed numbers, other are constants.

2023-12-20 20:36 UTC, rosteslav commented on src/Properties/Properties.Application/Mapper/PropertyProfile.cs
> +                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Property.Id))
this should be automatic with:
.ForMember(dest => dest, opt => opt.MapFrom(src => src.Property))
this will work for:
id, Neighbourhood, Price, NumberOfRooms, Space
Others should remain as is.

2023-12-21 08:30 UTC, viktorgkw commented on src/Properties/Properties.Application/Mapper/PropertyProfile.cs
> +                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Property.Id))
I'm not sure that works. It explodes

2023-12-21 22:10 UTC, rosteslav requested changes

2023-12-21 22:10 UTC, rosteslav commented on src/Properties/Properties.Application/Mapper/PropertyProfile.cs
> +                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Property.Id))
automapper is very powerful, it can do a lot of things. Knowing this you should try to find a way.
the solution I found is you should add:
`CreateMap<Property, GetAllPropertiesOutputModel>();`
then, having this
`CreateMap<PropertyDetailsWithImagesModel, GetAllPropertiesOutputModel>()`
`.IncludeMembers(src => src.Property)`
works fine

try it!

2023-12-21 22:10 UTC, rosteslav commented on src/Properties/Properties.Api/Controllers/PropertiesController.cs
**You didn't test this!
Test it, and I want you to find a huge bug!
Improve your testing!**

2023-12-22 07:35 UTC, viktorgkw commented on src/Properties/Properties.Api/Controllers/PropertiesController.cs
I didn't fully test it, because I was unsure about the mapper part since I never use AutoMapper. Now when it's done I will.

2023-12-22 17:30 UTC, rosteslav approved these changes

2023-12-22 17:30 UTC, merged