Feature/HM-95-Properties-Read images for properties from Redis
rosteslav/HomesBE pull request #84
Opened 2023-12-21 11:04 UTC by petarbelchev

The Properties microservice now gets images from Redis.

2023-12-23 17:08 UTC, rosteslav requested changes

2023-12-23 17:08 UTC, rosteslav commented on src/Properties/Properties.Application/Contracts/IPropertiesRepository.cs
> +        Task<IList<GetAllPropertiesOutputModel>> Get(GetAllPropertiesQuery query);
you need that, because you would want indexer this[], right?
you don't actually need it. get rid of that change

2023-12-23 17:08 UTC, rosteslav commented on src/Properties/Properties.Application/Features/Properties/Queries/GetAllProperties/GetAllPropertiesQueryHandler.cs
> +                    foreach (var property in propertiesImages)
Do it with for(;;) and you'll have index, based on properties, use that. propertiesImages is an array, it has index.

2023-12-23 17:08 UTC, rosteslav commented on src/Properties/Properties.Application/Features/Properties/Queries/GetAllProperties/GetAllPropertiesQueryHandler.cs
> +                    int index = 0;
this is a bit hacky

2023-12-23 17:08 UTC, rosteslav commented on src/Properties/Properties.Application/Features/Properties/Queries/GetById/GetByIdQueryHandler.cs
> +                    property.Images = propertiesImages.First().Images;
use .Single() when you expect enumerable to have only one item. Use .First() when you want the first of many!

2023-12-23 17:08 UTC, rosteslav commented on src/Properties/Properties.Application/Models/GetAllPropertiesOutputModel.cs
> -        public required string Neighbourhood { get; set; }
why you get rid of those

2023-12-23 17:08 UTC, rosteslav commented on src/Properties/Properties.Application/Features/Properties/Queries/GetAllProperties/GetAllPropertiesQueryHandler.cs
> +                    foreach (var property in propertiesImages)
This way is not super bad, but try it the other way around. If it doesn't work will do it this way

2023-12-23 17:08 UTC, rosteslav commented on src/Properties/Properties.Application/Features/Properties/Queries/GetAllProperties/GetAllPropertiesQueryHandler.cs
> +                    foreach (var property in propertiesImages)
Did you test it? Did it work?

2023-12-23 17:12 UTC, rosteslav requested changes

2023-12-23 17:12 UTC, rosteslav commented on src/Properties/Properties.Infrastructure/Repositories/PropertiesRepository.cs
> -                    .GroupJoin(_context.Images,
You may join here, as it was, but just not with _context.Images, with newly got images from redis

2023-12-23 17:55 UTC, petarbelchev commented on src/Properties/Properties.Application/Features/Properties/Queries/GetAllProperties/GetAllPropertiesQueryHandler.cs
> +                    foreach (var property in propertiesImages)
It is working. I did it this way because, for the compiler, the `propertiesImages` collection is `IEnumerable`, and I need to use `.ElementAt()` which will check for the existence of the indexer and use it, and will not iterate over the collection, but I decided to use the indexer explicitly. I will change it to use a "for loop".

2023-12-23 17:57 UTC, petarbelchev commented on src/Properties/Properties.Application/Contracts/IPropertiesRepository.cs
> +        Task<IList<GetAllPropertiesOutputModel>> Get(GetAllPropertiesQuery query);
Yes, that’s the reason. It will be reversed.

2023-12-23 17:58 UTC, petarbelchev commented on src/Properties/Properties.Application/Features/Properties/Queries/GetById/GetByIdQueryHandler.cs
> +                    property.Images = propertiesImages.First().Images;
Got it

2023-12-23 21:30 UTC, petarbelchev commented on src/Properties/Properties.Application/Models/GetAllPropertiesOutputModel.cs
> -        public required string Neighbourhood { get; set; }
There are no reasons for the current pull request, they were removed due to changes that ultimately are not present here, so I will return them…

2023-12-26 08:26 UTC, rosteslav approved these changes

2023-12-26 08:26 UTC, merged