Feature/HM-97-Properties-Method-that-accepts-model-like-PreferencesModel-and-returns-top-6-props-ids
rosteslav/HomesBE pull request #90
Opened 2023-12-27 11:52 UTC by petarbelchev

The Properties microservice uses Preferences Store and Recommended Repository.

2023-12-27 18:04 UTC, rosteslav requested changes

2023-12-27 18:04 UTC, rosteslav commented on src/Properties/Properties.Api/Controllers/PropertiesController.cs
> +            var properties = await _mediator.Send(new GetRecommendedQuery() { BuyerId = userId });
`(` `)` are not used when with `{` `}` 
In other words 
`new GetRecommendedQuery {BuyerId = userId}` without `()`

2023-12-27 18:04 UTC, rosteslav commented on src/Properties/Properties.Application/Models/PreferencesModel.cs
> +    public class PreferencesModel
this exists elsewhere.. if in other microservice, move it to common

2023-12-27 18:04 UTC, rosteslav commented on src/Properties/Properties.Infrastructure/InfrastructureServiceRegistration.cs
> +            services.AddScoped<IRecommendationRepository, RecommendationRepository>();
why not singleton, as well as the other repositories

2023-12-27 18:04 UTC, rosteslav commented on src/Properties/Properties.Application/Contracts/IPropertiesRepository.cs
> +        Task<IEnumerable<GetAllPropertiesOutputModel>> GetById(IEnumerable<int> ids, CancellationToken cancellationToken);
GetByIds, you have more than one

2023-12-27 18:04 UTC, rosteslav commented on src/Properties/Properties.Application/Features/Properties/Queries/GetRecommended/GetRecommendedQueryHandler.cs
>                  var propertyIds = properties.Select(p => p.Id.ToString()).ToArray();
You don't need that no more. you have it as `recommendedIds` above

2023-12-27 18:04 UTC, rosteslav commented on src/Properties/Properties.Infrastructure/Repositories/PropertiesRepository.cs
> +            {
check if `ids` is not null or count > 0, no need to go to the db if null or empty

2023-12-27 18:04 UTC, rosteslav commented on src/Properties/Properties.Infrastructure/Repositories/RecommendationRepository.cs
> +                    .OrderBy(p => p.Id)
first do a select:
`.Select(p => p.Id)`
`.OrderBy(i => i)`

2023-12-28 09:43 UTC, petarbelchev commented on src/Properties/Properties.Application/Features/Properties/Queries/GetRecommended/GetRecommendedQueryHandler.cs
>                  var propertyIds = properties.Select(p => p.Id.ToString()).ToArray();
Actually I need this operation (convert to string[]), because the store wants `string[]` and I think it is better to get the ids from the actual properties, instead of the `recommendedIds` collection?

2023-12-28 10:36 UTC, petarbelchev commented on src/Properties/Properties.Infrastructure/InfrastructureServiceRegistration.cs
> +            services.AddScoped<IRecommendationRepository, RecommendationRepository>();
I think exposing a repository as a singleton in a concurrent environment can be risky. The DbContext is not thread-safe. It is bad practice to have a single instance of the DbContext for the whole lifetime of the application. It is very important to dispose the DbContext and release the used resources after use?

2023-12-28 14:55 UTC, rosteslav commented on src/Properties/Properties.Infrastructure/InfrastructureServiceRegistration.cs
> +            services.AddScoped<IRecommendationRepository, RecommendationRepository>();
Yes, that's correct, I didn't consider we have a context in there

2023-12-28 14:57 UTC, rosteslav commented on src/Properties/Properties.Application/Features/Properties/Queries/GetRecommended/GetRecommendedQueryHandler.cs
>                  var propertyIds = properties.Select(p => p.Id.ToString()).ToArray();
yes, totally

2023-12-28 15:03 UTC, rosteslav approved these changes

2023-12-28 15:03 UTC, merged